Global:
  separators:
    input: [" ", "-", "_", ".", "/", "*", "@", "#", "$", "%", "&", "+", "=", "~", "|"]
    normalized: " "  # Use a single space for normalized output
    preserve: false  # Always normalize to the above
  case_normalization: "titlecase"  # Options: lowercase, uppercase, titlecase
  allow_multiple_separators: false

Name:
  use_global_separators: true
  extraction_order:
    - shorthand
    - initials
    - first_name
    - last_name

Date:
  use_global_separators: true
  format: "%Y-%m-%d"
  date_priority_order:
    - filename
    - foldername
    - modified
    - created 

Category:
  mapping_test_file: tests/fixtures/04_category_mapping.csv
  id_column: category_id
  name_column: category_name
  case_insensitive: true
  enabled: true
  first_level_only: true
  append_to_filename: true
  placement: suffix 

UserMapping:
  mapping_test_file: tests/fixtures/05_user_mapping.csv
  id_column: user_id
  name_column: full_name
  case_insensitive: true
  create_if_missing: false 