Global:
  separators:
    input: [" ", "-", "_", ".", "/", "*", "@", "#", "$", "%", "&", "+", "=", "~", "|"]
    normalized: " "  # Use a single space for normalized output
    preserve: false  # Always normalize to the above
  case_normalization: "titlecase"  # Options: lowercase, uppercase, titlecase
  allow_multiple_separators: false
  component_order:
    - id
    - name
    - remainder
    - date
    - category
  component_separator: "_"  # Separator between components in final filename
  file_exclusions:
    - "desktop.ini"
    - "Thumbs.db"
    - ".DS_Store"
    - "*.tmp"
    - "~$*"  # Temporary Office files

Name:
  use_global_separators: true
  extraction_order:
    - shorthand
    - initials
    - first_name
    - middle_name
    - last_name

Date:
  use_global_separators: true
  normalized_format: "%Y-%m-%d"  # Format to normalize all dates to
  allowed_formats:
    - "%Y-%m-%d"      # 2023-05-15
    - "%d-%m-%Y"      # 15-05-2023
    - "%Y%m%d"        # 20230515
    - "%d%m%Y"        # 15052023
    - "%m%d%Y"        # 05152023
    - "%d-%b-%Y"      # 15-May-2023
    - "%b-%d-%Y"      # May-15-2023
    - "%d %b %Y"      # 15 May 2023
    - "%B %d, %Y"     # May 15, 2023
    - "%Y.%m.%d"      # 2023.05.15
    - "%d.%m.%Y"      # 15.05.2023
    - "%d %B %Y"      # 15 May 2023
    - "%d-%B-%Y"      # 15-May-2023
    - "%d/%m/%Y"      # 15/05/2023
    - "%Y/%m/%d"      # 2023/05/15
    - "%d.%m.%y"      # 25.01.15 or 5.9.24 (2-digit year, single or double digit day/month)
    - "%d/%m/%y"      # 25/01/15 or 5/9/24 (2-digit year, single or double digit day/month)
    - "%d-%m-%y"      # 25-01-15 or 5-9-24 (2-digit year, single or double digit day/month)
  date_priority_order:
    - filename
    - foldername
    - modified
    - created
  exclude_ranges: true
  excluded_date_by_prefix:
    - "exp"
  exclude_ranges_separators:
    - " "
    - "-"
    - "_"
    - "."
    - ","
    - "to"
  exclude_ranges_separator_strings:
    - " to "
  exclude_ranges_normalized_separator: " - "

Category:
  mapping_test_file: tests/fixtures/04_category_mapping.csv
  id_column: category_id
  name_column: category_name
  case_insensitive: true
  enabled: true
  first_level_only: true
  append_to_filename: true
  placement: suffix 

UserMapping:
  mapping_test_file: tests/fixtures/05_user_mapping.csv
  id_column: user_id
  name_column: full_name
  case_insensitive: true
  create_if_missing: false
  prefix: "VC - "  # Optional prefix to remove from directory names
  suffix: " Management"  # Optional suffix to remove from directory names 